apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: r3x-rubix-list
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/muldoon/r3x-rubix-list