version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/rubix
    steps:
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-dependencies
          command: npm install
